#source 'https://git.coding.net/hging/Specs.git'

# coding: utf-8
platform :ios, '7.0'

target :{{args.ProductName}} do
  pod 'HTToast' 
  pod 'HTBadgeTextView' 
  pod 'UniversalRouter' 
  pod 'HTR3'
  pod 'HTPageControllerView' 
  pod 'HTImageView' 
  pod 'HTSegmentsView'
  pod 'HTRefreshView' 
  pod 'HTCommonUtility'
  pod 'HTNetworking'
  pod 'HTAssetsPicker'
  pod 'HTTableViewDataSourceDelegate'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
  pod 'BlocksKit' ,  '~>2.2.5'
  pod 'IQKeyboardManager' , '~>3.3.7'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'MGSwipeTableCell', '1.5.1'
  pod 'Masonry'
  pod 'SDWebImage/WebP'
  pod 'libwebp', '~>0.4.3'
  pod 'pop', '1.0.7'
end
